
export let component_names: string[] =
[
	undefined,
		"Controllable Physics",
    "Render",
    "Simple Physics",
    "Character",
    "Script",
    "Bouncer",
    "Destroyable",
    "Ghost",
    "Skill",
    "Spawner",
    "Item",
    "Rebuild",
    "Rebuild Start",
    "Rebuild Activator",
    "Icon Only",
    "Vendor",
    "Inventory",
    "Projectile Physics",
    "Shooting Gallery",
    "RigidBodyPhantomPhysics",
    "Drop Effect",
    "Chest",
    "Collectible",
    "Blueprint",
    "Moving Platform",
    "Pet",
    "Platform Boundary",
    "Module",
    "Arcade",
    "Vehicle Physics",
    "MovementAI",
    "Exhibit",
    "OverheadIcon",
    "Pet Control",
    "Minifig",
    "Property",
    "Pet Creator",
    "Model Builder",
    "Scripted Activity",
    "Phantom Physics",
    "Springpad",
    "B3 Behaviors",
    "Property Entrance",
    "FX",
    "Property Management",
    "Vehicle Physics",
    "Physics System",
    "Quick Build",
    "Switch",
    "Minigame",
    "Changling",
    "Choice Build",
    "Package",
    "Sound Repeater",
    "Sound Ambient 2D",
    "Sound Ambient 3D",
    "Precondition",
    "Player Flags",
    "Custom Build Assembly",
    "Base Combat AI",
    "Module Assembly",
    "Showcase Model Handler",
    "Racing Module",
    "Generic Activator",
    "Property Vendor",
    "HFLightDirectionGadget",
    "Rocket Launch",
    "Rocket Landing",
    "Trigger",
    "Dropped Loot",
    "Racing Control",
    "Faction Trigger",
    "Mission Offer",
    "Racing Stats",
    "LUP Exhibit",
    "BBB",
    "Sound Trigger",
    "Proximity Monitor",
    "Racing Sound Trigger",
    "Chat",
    "Friends List",
    "Guild",
    "Local System",
    "Mission",
    "Mutable Model Behaviors",
    "Pathfinding Control",
    "Pet Taming Control",
    "Property Editor",
    "Skinned Render",
    "Slash Command",
    "Status Effect",
    "Teams",
    "Text Effect",
    "Trade",
    "User Control",
    undefined,
    "LUP Launchpad",
    undefined,
    undefined,
    "Brick Donation",
    undefined,
    "Commendation Vendor",
    undefined,
    "Rail Activator",
    "Roller",
    "Unknown",
    "Unknown",
    "Possessable",
    undefined,
    undefined,
    undefined,
    undefined,
    "Property Plaque",
    "Build Border",
    undefined,
    "Culling Plane"
];
