import { Zone } from './zone';

export const ZONES: Zone[] = [
  { id: 1000, display: 'Venture Explorer' },
  { id: 1001, display: 'Return to Venture Explorer' },
  { id: 1100, display: 'Avant Gardens' },
  { id: 1101, display: 'Avant Gardens Survival' },
  { id: 1102, display: 'Spider Queen Battle' },
  { id: 1150, display: 'Block Yard' },
  { id: 1151, display: 'Avant Grove' },
  { id: 1200, display: 'Nimbus Station' },
  { id: 1201, display: 'Pet Cove' },
  { id: 1203, display: 'Vertigo Loop Racetrack' },
  { id: 1204, display: 'Battle of Nimbus Station' },
  { id: 1250, display: 'Nimbus Rock' },
  { id: 1251, display: 'Nimbus Isle' },
  { id: 1260, display: 'Frostburgh' },
  { id: 1300, display: 'Gnarled Forest' },
  { id: 1302, display: 'Canyon Cove' },
  { id: 1303, display: 'Keelhaul' },
  { id: 1350, display: 'Chantey Shantey' },
  { id: 1400, display: 'Forbidden Valley' },
  { id: 1402, display: 'Forbidden Valley Dragon' },
  { id: 1403, display: 'Dragonmaw Chasm' },
  { id: 1450, display: 'Raven Bluff' },
  { id: 1600, display: 'Starbase 3001' },
  { id: 1601, display: 'Deep Freeze' },
  { id: 1602, display: 'Robot City' },
  { id: 1603, display: 'Moon Base' },
  { id: 1604, display: 'Portabello' },
  { id: 1700, display: 'LEGO Club' },
  { id: 1800, display: 'Crux Prime' },
  { id: 1900, display: 'Nexus Tower' },
  { id: 2000, display: 'Ninjago' },
  { id: 2001, display: 'Frakjaw Battle' }
];