name: Build the app
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: lu-explorer
          path: dist
